# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b21162d1ca9e51c9bcd7ebc2853b4be1917b9f87a2c59194e81756a5a4813b7f41479885d6a9fa4c4b31ebbce16eaab1baa849db7181459fb79b9e254b858d00

test:
  secret_key_base: c244ea8c0b508e5600c9a9efc506a98d1e5594534f0338668f575b0c1e0a4126fcd632139c3f998ce14a51382c1dac6311ac073c74b9bf7e727aeac0c24302b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
